platform :ios, '7.0'
target 'QQZone' do
    
##
pod 'AFNetworking', '~> 3.1.0'

##
pod 'SDWebImage', '~> 3.7.2'

##
pod 'MJExtension'

##
pod 'Masonry'

##
pod 'MJRefresh'

##
pod 'MBProgressHUD'

end


