platform :ios, '11.0'

#install! 'cocoapods', :disable_input_output_paths => true
install! 'cocoapods', disable_input_output_paths: true, generate_multiple_pod_projects: true

target 'Media' do
    
##
pod 'AFNetworking', '~> 3.1.0'

##
pod 'SDWebImage', '~> 4.3.3'

##
pod 'MJExtension'

##
pod 'Masonry'

##
pod 'MJRefresh'

##
pod 'MBProgressHUD'

##
pod 'SJVideoPlayer'
#pod 'SJBaseVideoPlayer'

end


