platform :ios, '7.0'
target 'Media' do
    
##
pod 'AFNetworking', '~> 3.1.0'

##
pod 'SDWebImage', '~> 4.3.3'

##
pod 'MJExtension'

##
pod 'Masonry'

##
pod 'MJRefresh'

##
pod 'MBProgressHUD'

end


